// Azura World CATI — frozen interfaces.
//
// This file is the EXECUTABLE FORM of `CONTRACTS.md`. The document is the
// specification; this file is the implementation. They must not drift.
//
// Owned by W0-A. Every parallel window compiles against this file. It does not
// change during a wave: if a contract here is wrong, stop, report, amend
// `CONTRACTS.md` centrally, bump CONTRACT_VERSION, restart affected tasks
// (ORCHESTRATION §7). Do not edit this file to make your own code compile.
//
// Dependency-free on purpose — no imports, no Node built-ins, no filesystem.
// It is therefore safe in both the server and the client bundle, and it can be
// loaded by `node --experimental-strip-types` (which means: no `enum`, no
// `namespace`, and no constructor parameter properties in this file, ever).

/** Version of the frozen contract surface. Bumped only by a central amendment. */
export const CONTRACT_VERSION = 1 as const

// ---------------------------------------------------------------------------
// 1. Provenance
// ---------------------------------------------------------------------------

/** How well established a fact is. `"gap"` MUST carry `value === null`. */
export type Confidence =
  | "confirmed" // ≥2 independent sources agree
  | "official" // stated by azuraworld.com or a Cebeci Group domain
  | "single_source" // one source only, uncontradicted
  | "conflicted" // sources disagree; see conflictsWith
  | "inferred" // derived by computation from confirmed facts; note explains how
  | "gap" // not established — value MUST be null

/** Resolution order when sources disagree. Lower number wins the DISPLAY value. */
export type SourceTier =
  | 1 // official        — azuraworld.com
  | 2 // developer       — cebecigroup.com, alanyacebeci.com
  | 3 // hotel operation — azuraworldhotel.com
  | 4 // portal          — terra, alanya-home, housearch, haspo, seaside, realtygroup, ivm
  | 5 // review/booking  — tripadvisor, booking, agoda, onthebeach
  | 6 // press/secondary — enspride, turizmguncel, kalinka, cestate

/** One citation: where a value came from and the snapshot that proves it. */
export interface SourceRef {
  url: string
  /** Publisher label for UI, e.g. "Seaside Alanya" */
  publisher: string
  /** ISO 8601. When the harvester actually retrieved this. */
  fetchedAt: string
  /** sha256 of the stored raw snapshot under sources/raw/ */
  snapshotHash: string
  tier: SourceTier
}

/** A value that cannot be displayed without the sources that produced it. */
export interface SourcedFact<T> {
  value: T | null
  sources: SourceRef[]
  confidence: Confidence
  /** Populated iff confidence === "conflicted". Never empty when it is. */
  conflictsWith?: Array<{ value: unknown; source: SourceRef }>
  /** Required for "inferred" and "gap". Explains the derivation or the absence. */
  note?: string
}

// ---------------------------------------------------------------------------
// 2. Dataset
// ---------------------------------------------------------------------------

// CONTRACT-GAP-01 / CONTRACT-GAP-02 — grep these ids.
//
// `AzuraWorldDataset.blocks` is typed `AzuraBlock[]` and `.amenities` is typed
// `Amenity[]` in CONTRACTS.md §2, but NEITHER interface is defined anywhere in
// that document. They are declared here as open records rather than invented
// shapes: this file transcribes the specification, it does not extend it.
//
// Consequence for downstream windows: you can carry these values around, but
// you cannot read a named property off one without a cast, and you must not add
// one here. Before any window relies on specific fields, CONTRACTS.md must be
// amended centrally and CONTRACT_VERSION bumped (ORCHESTRATION §8). Reported in
// HANDOFF/W0-A.md.

/** CONTRACT-GAP-01 — referenced by CONTRACTS.md §2 but never defined there. */
export type AzuraBlock = Record<string, unknown>

/** CONTRACT-GAP-02 — referenced by CONTRACTS.md §2 but never defined there. */
export type Amenity = Record<string, unknown>

/** The whole generated dataset. Generated file — never hand-edit; fix the parser. */
export interface AzuraWorldDataset {
  generatedAt: string
  contractVersion: 1
  harvest: HarvestEntry[]
  project: AzuraProject
  blocks: AzuraBlock[]
  units: AzuraUnit[]
  hotel: AzuraHotel
  reviews: ReviewSource[]
  portalListings: PortalListing[]
  amenities: Amenity[]
  findings: Finding[]
}

/** One harvester attempt against one URL, successful or not. */
export interface HarvestEntry {
  url: string
  publisher: string
  tier: SourceTier
  /** HTTP status, or a transport error label: "dns_timeout" | "tls_invalid" | "blocked_403" */
  status: number | string
  fetchedAt: string
  snapshotPath: string | null
  snapshotHash: string | null
  bytes: number
  /** false when the body was a soft-404 or bot wall wearing a 200 */
  contentValidated: boolean
}

/** The project record. Every uncertain figure is a `SourcedFact`. */
export interface AzuraProject {
  name: string // "Azura World Residence & Hotel"
  code: "AZW-TRK"
  developer: SourcedFact<string>
  developerFoundedYear: SourcedFact<number>
  country: "Türkiye"
  province: "Antalya"
  city: "Alanya"
  district: "Türkler"
  plotAreaSqm: SourcedFact<number>
  greenAreaSqm: SourcedFact<number>
  buildingFootprintSqm: SourcedFact<number>
  outdoorFacilityAreaSqm: SourcedFact<number>
  residenceBlockCount: SourcedFact<number>
  buildingCount: SourcedFact<number>
  floorsPerBuilding: SourcedFact<number>
  totalUnits: SourcedFact<number>
  constructionStart: SourcedFact<string> // ISO date
  completionDate: SourcedFact<string> // ISO date
  buildStatus: SourcedFact<"planned" | "under_construction" | "completed">
  distanceToSeaM: SourcedFact<number>
  distanceToAlanyaCentreKm: SourcedFact<number>
  distanceToGazipasaAirportKm: SourcedFact<number>
  distanceToAntalyaAirportKm: SourcedFact<number>
  downPaymentPercent: SourcedFact<number>
  contact: {
    phone: SourcedFact<string>
    email: SourcedFact<string>
    address: SourcedFact<string>
  }
  social: Array<{ platform: string; url: string; source: SourceRef }>
}

/** Turkish notation: rooms+living. "1+1" = 1 bedroom + 1 living room. */
export type UnitLayout =
  | "1+1"
  | "2+1"
  | "3+1"
  | "4+1"
  | "5+1"
  | "6+1"
  | "penthouse"
  | "townhouse"
  | "villa"
  | "president_villa"

/** One sellable unit. `dataQuality` says whether it is real or modelled. */
export interface AzuraUnit {
  id: string // "AZW-B03-0412"
  blockCode: string
  sequence: number
  layout: UnitLayout
  interiorM2: number | null
  outdoorM2: number | null
  floorLevel: number | null
  askingPrice: SourcedFact<Money>
  /** Same unit priced differently by different portals. Always keep all of them. */
  competingPrices: Array<{ money: Money; source: SourceRef; observedAt: string }>
  saleStatus: SourcedFact<"available" | "reserved" | "sold" | "unknown">
  /** "portal_listing" = a real scraped listing. "modelled" = synthesised to fill the
   *  656-unit inventory; NEVER presented as a real listing. */
  dataQuality: "portal_listing" | "official" | "modelled" | "source_missing"
}

/** An amount and its currency. Never convert silently — convert only at display. */
export interface Money {
  amount: number
  currency: "EUR" | "USD" | "TRY" | "GBP"
}

/** The on-site hotel. The Wyndham → Azura rebrand is itself a finding. */
export interface AzuraHotel {
  name: SourcedFact<string> // "Azura World Hotel"
  formerName: SourcedFact<string> // "Wyndham Alanya" — the rebrand is a finding
  stars: SourcedFact<number>
  roomCount: SourcedFact<number>
  floors: SourcedFact<number>
  openedYear: SourcedFact<number>
  board: SourcedFact<string> // "All Inclusive"
  aquaparkSlides: SourcedFact<number>
  distanceToBeachM: SourcedFact<number>
  checkIn: SourcedFact<string>
  checkOut: SourcedFact<string>
  brandAffiliation: SourcedFact<string | null>
}

/** One review platform's scores and verbatim quotes. Never paraphrase a review. */
export interface ReviewSource {
  platform: "tripadvisor" | "booking" | "agoda" | "onthebeach" | "google"
  url: string
  score: SourcedFact<number>
  scoreScale: 5 | 10
  reviewCount: SourcedFact<number>
  ranking: SourcedFact<string> // "#10 of 33 hotels in Türkler"
  sentiment: { positive: number; mixed: number; negative: number } | null
  /** Verbatim quotes with permalinks. Never paraphrase a review. */
  notableQuotes: Array<{
    text: string
    rating: number
    date: string
    url: string
  }>
}

/** A third-party portal's own claims, kept verbatim for the conflict register. */
export interface PortalListing {
  publisher: string
  url: string
  fetchedAt: string
  layout: UnitLayout | null
  interiorM2: number | null
  price: Money | null
  /** Portal's own claim about the project, kept for the conflict register */
  claimedBlockCount: number | null
  claimedTotalUnits: number | null
  claimedBuildStatus: string | null
  isStale: boolean // contradicts a tier ≤3 source
}

/** A recorded disagreement or defect. Findings are never silently resolved. */
export interface Finding {
  id: string // "F-001"
  severity: "critical" | "high" | "medium" | "low" | "info"
  area:
    | "structure"
    | "pricing"
    | "timeline"
    | "geography"
    | "branding"
    | "availability"
    | "harvest"
  field: string // dotted path: "project.residenceBlockCount"
  message: string
  competingValues: Array<{ value: unknown; source: SourceRef }>
  resolution: string
  // NOTE: CONTRACTS.md §2 writes `resolvedTo: unknown | null`. That union
  // reduces to exactly `unknown` in TypeScript (`null` is already assignable to
  // `unknown`), so it is written as `unknown` here — identical semantics, and it
  // avoids a redundant-type-constituent lint error. `null` still carries the
  // documented meaning: deliberately unresolved.
  resolvedTo: unknown // null = deliberately unresolved
}

// ---------------------------------------------------------------------------
// 3. RBAC — frozen. W1-B (TS) and W1-A (SQL) must agree exactly.
// ---------------------------------------------------------------------------

/** Eleven roles. The TS union and the SQL enum are the same list in this order. */
export const roles = [
  "admin",
  "manager",
  "accountant",
  "staff",
  "owner",
  "tenant",
  "guest",
  "service_provider",
  "child_owner",
  "child_tenant",
  "child_guest",
] as const

/** Permission-bearing surfaces. `evidence` gates the source/conflict cockpit. */
export const resources = [
  "dashboard",
  "listings",
  "units",
  "leads",
  "buyer_pipeline",
  "deals",
  "tickets",
  "activities",
  "calendar",
  "documents",
  "compliance",
  "finance",
  "wallet",
  "vendor_invoices",
  "reports",
  "users",
  "settings",
  "communications",
  "hotel",
  "reviews",
  "evidence",
] as const

/** The eight verbs a role may hold against a resource. */
export const actions = [
  "view",
  "create",
  "update",
  "delete",
  "manage",
  "export",
  "approve",
  "assign",
] as const

/** One of the eleven frozen roles. */
export type Role = (typeof roles)[number]

/** One of the frozen permission-bearing surfaces. */
export type Resource = (typeof resources)[number]

/** One of the eight frozen verbs. */
export type Action = (typeof actions)[number]

/** A permission string, e.g. "evidence:view". */
export type Permission = `${Resource}:${Action}`

/**
 * Numeric authority of each role (higher = broader). The five added roles
 * (`guest`, `service_provider`, `child_*`) sit strictly below the canonical six
 * and may never widen an existing role's permissions.
 *
 * These are the values in CONTRACTS.md §3, transcribed verbatim. They differ
 * from the 1Çatı reference `lib/rbac.ts` — do not copy that file's numbers.
 */
export const roleLevel: Record<Role, number> = {
  admin: 90,
  manager: 70,
  accountant: 60,
  staff: 40,
  owner: 20,
  tenant: 10,
  service_provider: 30,
  guest: 5,
  child_owner: 15,
  child_tenant: 8,
  child_guest: 3,
}

// ---------------------------------------------------------------------------
// 4. Repository envelope
// ---------------------------------------------------------------------------

/**
 * Every repository function returns this. Never throw for "Supabase not
 * configured" — fall back to the local seed and label it. Do throw when a
 * *configured* Supabase returns a real error; a silent fallback hides an outage.
 */
export interface RepositoryResult<T> {
  data: T
  source: "supabase" | "local-seed"
  /** Present when source === "local-seed" AND Supabase was expected. Explains the fallback. */
  degradedReason?: string
  fetchedAt: string
}

// ---------------------------------------------------------------------------
// 5. API envelope
// ---------------------------------------------------------------------------

/** Discriminated API envelope. Check `ok` before touching `data` or `error`. */
export type ApiResponse<T> =
  | { ok: true; data: T; source: "supabase" | "local-seed"; requestId: string }
  | { ok: false; error: ApiError; requestId: string }

/** A handled failure. Never 500 for one of these — a 500 means we have a bug. */
export interface ApiError {
  code:
    | "unauthorized"
    | "forbidden"
    | "not_found"
    | "validation_failed"
    | "rate_limited"
    | "conflict"
    | "persistence_unavailable"
    | "upstream_failed"
  message: string // safe for display; never contains internals
  details?: Record<string, string>
  retryable: boolean
}

/** Fixed code → HTTP status mapping from CONTRACTS.md §5. Frozen; tested by W4-D. */
export const apiErrorStatus: Record<ApiError["code"], number> = Object.freeze({
  unauthorized: 401,
  forbidden: 403,
  not_found: 404,
  validation_failed: 422,
  conflict: 409,
  rate_limited: 429,
  persistence_unavailable: 503,
  upstream_failed: 502,
})

// ---------------------------------------------------------------------------
// 6. AI
// ---------------------------------------------------------------------------

/** Concierge input. Ceiling of 2000 chars on `message`, validated before anything else. */
export interface AiRequest {
  message: string
  conversationId?: string
  locale: Locale
}

/** Concierge output. RBAC is decided before the gateway call, never after. */
export interface AiResponse {
  reply: string
  source: "gateway" | "deterministic-fallback" | "rbac-guard"
  /** Every factual claim traced to dataset provenance. Empty ⟹ reply asserted no facts. */
  citations: SourceRef[]
  model: string | null
  refused: boolean
  refusalReason?:
    | "out_of_scope"
    | "insufficient_permission"
    | "no_grounding"
    | "unsafe_request"
}

// ---------------------------------------------------------------------------
// 7. Locale
// ---------------------------------------------------------------------------

/** Supported locales. `localePrefix: "always"` — every URL carries its locale. */
export const locales = ["de", "en", "tr", "ru"] as const

/** One of the four supported locales. */
export type Locale = (typeof locales)[number]

/** German is default: the ticket is German and 5 of 7 portal sources are German. */
export const defaultLocale: Locale = "de"

// ---------------------------------------------------------------------------
// Runtime guards
// ---------------------------------------------------------------------------

/** Options for `assertFactInvariants`. */
export interface AssertFactOptions {
  /** Invariant 6. When supplied, every source's snapshotHash is checked against it.
   *  W0-B's verify-evidence.mjs and W4-D's contract suite supply a real fs-backed resolver. */
  snapshotExists?: (snapshotHash: string) => boolean
}

/**
 * Thrown by `assertFactInvariants`. Carries the dotted `path` of the offending
 * fact and the number (1–6) of the CONTRACTS.md §1 invariant that fired, so a
 * test can assert *which* rule broke rather than only that something threw.
 */
export class FactInvariantError extends Error {
  /** Dotted path of the offending fact, e.g. "project.residenceBlockCount". */
  readonly path: string
  /** Which CONTRACTS.md §1 invariant fired (1–6). */
  readonly invariant: 1 | 2 | 3 | 4 | 5 | 6

  constructor(invariant: 1 | 2 | 3 | 4 | 5 | 6, path: string, reason: string) {
    super(`SourcedFact invariant ${invariant} violated at ${path}: ${reason}`)
    this.name = "FactInvariantError"
    this.path = path
    this.invariant = invariant
  }
}

/** sha256, lower-case hex. The shape every `SourceRef.snapshotHash` must have. */
const SNAPSHOT_HASH_PATTERN = /^[0-9a-f]{64}$/

const CONFIDENCE_VALUES = [
  "confirmed",
  "official",
  "single_source",
  "conflicted",
  "inferred",
  "gap",
] as const

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function isUnknownArray(value: unknown): value is readonly unknown[] {
  return Array.isArray(value)
}

function isConfidence(value: unknown): value is Confidence {
  if (typeof value !== "string") return false
  return CONFIDENCE_VALUES.some((candidate) => candidate === value)
}

function isSourceTier(value: unknown): value is SourceTier {
  return (
    value === 1 ||
    value === 2 ||
    value === 3 ||
    value === 4 ||
    value === 5 ||
    value === 6
  )
}

function isSourceRef(value: unknown): value is SourceRef {
  if (!isRecord(value)) return false
  return (
    typeof value["url"] === "string" &&
    typeof value["publisher"] === "string" &&
    typeof value["fetchedAt"] === "string" &&
    typeof value["snapshotHash"] === "string" &&
    isSourceTier(value["tier"])
  )
}

/**
 * Lower-cased hostname of a source URL, for invariant 3's "distinct hosts" test.
 * A URL that does not parse is itself a violation — a citation you cannot
 * re-open is not a citation — and is reported under invariant 3, the only
 * invariant that needs hostnames.
 */
function hostname(source: SourceRef, path: string): string {
  try {
    return new URL(source.url).hostname.toLowerCase()
  } catch {
    throw new FactInvariantError(
      3,
      path,
      `source url is not a parseable URL: ${JSON.stringify(source.url)}`
    )
  }
}

/**
 * Structural check that `v` is a `SourcedFact`. The generic `T` is not and
 * cannot be checked at runtime — this narrows the envelope, not the value.
 */
export function isSourcedFact<T>(v: unknown): v is SourcedFact<T> {
  if (!isRecord(v)) return false
  if (!("value" in v)) return false
  if (!isConfidence(v["confidence"])) return false

  const sources = v["sources"]
  if (!isUnknownArray(sources)) return false
  if (!sources.every(isSourceRef)) return false

  const conflictsWith = v["conflictsWith"]
  if (conflictsWith !== undefined && !isUnknownArray(conflictsWith)) return false

  const note = v["note"]
  if (note !== undefined && typeof note !== "string") return false

  return true
}

/**
 * Enforces all six `SourcedFact` invariants from CONTRACTS.md §1 and throws a
 * `FactInvariantError` naming the dotted `path` and the invariant number.
 *
 * Invariant 6 ("every snapshotHash resolves to a real file under sources/raw/")
 * cannot be checked from a browser-safe, filesystem-free module. It is split:
 * the *shape* of every snapshotHash (64 lower-case hex chars) is always
 * enforced, so a malformed hash is caught everywhere; *existence* is enforced
 * only when `options.snapshotExists` is supplied. Callers with filesystem
 * access — W0-B's verify-evidence.mjs and W4-D's contract suite — must supply
 * it, or invariant 6 is only half-enforced.
 */
export function assertFactInvariants<T>(
  f: SourcedFact<T>,
  path: string,
  options?: AssertFactOptions
): void {
  const note = typeof f.note === "string" ? f.note.trim() : ""

  // 1. gap ⟹ value === null and note is non-empty.
  if (f.confidence === "gap") {
    if (f.value !== null) {
      throw new FactInvariantError(
        1,
        path,
        'confidence is "gap" but value is not null'
      )
    }
    if (note.length === 0) {
      throw new FactInvariantError(
        1,
        path,
        'confidence is "gap" but note is missing or blank'
      )
    }
  }

  // 2. conflicted ⟹ conflictsWith.length >= 1.
  if (f.confidence === "conflicted") {
    const conflicts = f.conflictsWith
    if (conflicts === undefined || conflicts.length < 1) {
      throw new FactInvariantError(
        2,
        path,
        'confidence is "conflicted" but conflictsWith is empty or absent'
      )
    }
  }

  // 3. confirmed ⟹ sources.length >= 2 with distinct hosts.
  // Hosts are extracted for every fact so an unparseable citation URL is caught
  // regardless of confidence; the >= 2 rule applies only to "confirmed".
  const hosts = new Set<string>()
  for (const source of f.sources) {
    hosts.add(hostname(source, path))
  }
  if (f.confidence === "confirmed") {
    if (f.sources.length < 2) {
      throw new FactInvariantError(
        3,
        path,
        `confidence is "confirmed" but there are only ${f.sources.length} source(s)`
      )
    }
    if (hosts.size < 2) {
      throw new FactInvariantError(
        3,
        path,
        `confidence is "confirmed" but all ${f.sources.length} sources share the host "${
          Array.from(hosts)[0] ?? ""
        }"`
      )
    }
  }

  // 4. inferred ⟹ note explains the computation.
  if (f.confidence === "inferred" && note.length === 0) {
    throw new FactInvariantError(
      4,
      path,
      'confidence is "inferred" but note is missing or blank'
    )
  }

  // 5. sources.length === 0 is only legal when confidence === "gap".
  if (f.sources.length === 0 && f.confidence !== "gap") {
    throw new FactInvariantError(
      5,
      path,
      `sources is empty but confidence is "${f.confidence}"`
    )
  }

  // 6. Every snapshotHash resolves to a real file under sources/raw/.
  const snapshotExists = options?.snapshotExists
  for (const source of f.sources) {
    const hash = source.snapshotHash
    if (!SNAPSHOT_HASH_PATTERN.test(hash)) {
      throw new FactInvariantError(
        6,
        path,
        `snapshotHash ${JSON.stringify(hash)} for ${source.url} is not 64 lower-case hex characters`
      )
    }
    if (snapshotExists !== undefined && !snapshotExists(hash)) {
      throw new FactInvariantError(
        6,
        path,
        `snapshotHash ${hash} for ${source.url} does not resolve to a file under sources/raw/`
      )
    }
  }
}

/**
 * The value safe to render. Returns `null` for a `"gap"` regardless of what is
 * stored, so a gap can never leak a stale value into the UI.
 */
export function displayValue<T>(f: SourcedFact<T>): T | null {
  if (f.confidence === "gap") return null
  return f.value
}

/**
 * Picks the source that wins the DISPLAY value: the lower `tier` number wins.
 *
 * Tie-break, chosen so the function is total and deterministic:
 *   1. equal tier → the more recent `fetchedAt` wins;
 *   2. equal or unparseable `fetchedAt` → `a` wins, so the result is stable and
 *      the function is a valid reducer regardless of argument order noise.
 * The losing source is never discarded — CONTRACTS.md §8 requires it stay
 * stored and visible on demand.
 */
export function tierWins(a: SourceRef, b: SourceRef): SourceRef {
  if (a.tier !== b.tier) return a.tier < b.tier ? a : b

  const aFetched = Date.parse(a.fetchedAt)
  const bFetched = Date.parse(b.fetchedAt)
  if (Number.isNaN(aFetched) || Number.isNaN(bFetched)) return a
  if (aFetched !== bFetched) return aFetched > bFetched ? a : b

  return a
}
