/**
 * Turn an internal analyst note into something a client can read.
 *                                                          Owner: W-NIGHT
 *
 * ## The problem this exists to remove
 *
 * `lib/azura-world-data.ts` is a GENERATED dataset and its `note` fields are
 * written in English, for an analyst, about our own pipeline. Forty-three
 * distinct notes across 1,364 rows. Two surfaces render them verbatim to the
 * user, and this is what a German-speaking property manager currently reads on
 * `/dashboard/listings` and `/dashboard/evidence`:
 *
 *   "WRONG-DISTRICT SUSPECT: Azura World is in Türkler, Alanya; the page states
 *    district 'Oba', not Türkler. Emitted unchanged so the builder can decide."
 *
 *   "page states the layout as '5+ rooms', which is outside the frozen
 *    UnitLayout union"
 *
 *   "portal overview 'price from' row; the page does not attach this price to a
 *    layout; listing last updated 2023-02-25 16:50:01"
 *
 * "the frozen UnitLayout union" is a TypeScript type. "Emitted unchanged so the
 * builder can decide" is an instruction to a developer. This is an application
 * for people who run a building, and none of that is addressed to them.
 *
 * ## What it does instead
 *
 * Classifies the note into one of eighteen kinds by pattern, and the UI renders
 * a translated plain-language sentence for that kind. The original text is not
 * thrown away: `DataNote` keeps it behind a disclosure, labelled as the internal
 * wording, so an analyst who wants the detail still has it and nobody else has
 * to read it.
 *
 * ## Why a classifier and not a translation table
 *
 * Twenty-four of the forty-three notes are the same sentence with a different
 * URL in it, and the dataset is regenerated by a harvester. Keying on exact
 * strings would break on the next run and silently fall back to English. Keying
 * on the stable phrase survives it.
 *
 * ORDER MATTERS. The patterns are tested top to bottom and several notes match
 * more than one: a `MODELLED` note also contains "No source publishes". The
 * more specific claim has to win, so do not reorder without reading why.
 *
 * ## The honesty rule this is held to
 *
 * Plain language must make a limitation MORE obvious, never less. "Modellierter
 * Datensatz, kein echtes Inserat" is clearer than "MODELLED, NOT A LISTING",
 * not softer. If a rewrite would hide a caveat, the caveat wins and the sentence
 * gets longer. Anything unrecognised returns `null`, and `DataNote` then shows
 * the original rather than inventing a summary of a note it did not understand.
 */

/** The plain-language kinds. Each has a `dataNote.<kind>` message key. */
export type DataNoteKind =
  | "modelled"
  | "noAvailability"
  | "liveListing"
  | "conflicted"
  | "blockSplit"
  | "groupEntryPrice"
  | "cardFromPrice"
  | "portalPriceFrom"
  | "asPublished"
  | "wrongDistrict"
  | "rentNotSale"
  | "monthlyRent"
  | "implausibleArea"
  | "layoutUnspecific"
  | "noFloor"
  | "villaFloor"
  | "noChain"
  | "noRanking"

/**
 * Ordered, most specific first.
 *
 * Each entry is [kind, phrase]. Matching is case-sensitive on a phrase chosen to
 * be stable across harvester runs — no dates, no URLs, no counts.
 */
const PATTERNS: ReadonlyArray<readonly [DataNoteKind, string]> = [
  // Must precede `noAvailability`: a MODELLED note contains that phrase too.
  ["modelled", "MODELLED, NOT A LISTING"],
  ["wrongDistrict", "WRONG-DISTRICT SUSPECT"],
  ["blockSplit", "Block composition is not published"],
  ["conflicted", "Sources disagree."],
  ["liveListing", "A live listing implies availability"],
  ["noAvailability", "No source publishes unit-level availability"],
  ["groupEntryPrice", "advertised entry price for this floor-plan group"],
  ["cardFromPrice", "price for a project listing card"],
  ["portalPriceFrom", "portal overview 'price from' row"],
  // Must follow the rent patterns: a rent listing also carries a price.
  ["rentNotSale", "tags this listing as RENT"],
  ["monthlyRent", "monthly rent for one furnished apartment"],
  ["asPublished", "as published by"],
  ["implausibleArea", "is implausible for a"],
  ["layoutUnspecific", "outside the frozen UnitLayout union"],
  ["villaFloor", "is not a floor level"],
  ["noFloor", "states no floor for this unit"],
  ["noChain", "No CURRENT chain affiliation"],
  ["noRanking", "No ranking stated."],
]

/**
 * The kind of an internal note, or `null` if it is not one we recognise.
 *
 * `null` is a real answer and the caller must handle it: an unrecognised note is
 * shown as-is rather than summarised, because a wrong summary of a caveat is
 * worse than an unpolished true one.
 */
export function classifyDataNote(note: string | null | undefined): DataNoteKind | null {
  if (note === null || note === undefined) return null
  const text = note.trim()
  if (text.length === 0) return null
  for (const [kind, phrase] of PATTERNS) {
    if (text.includes(phrase)) return kind
  }
  return null
}

/**
 * The first URL in a note, if it carries one.
 *
 * Twenty-four `asPublished` notes name the page they were read from. That URL is
 * the single most useful thing in the note for a reader who wants to check it,
 * and it survives translation untouched, so it is lifted out and rendered as a
 * real link rather than left inside a sentence nobody reads.
 */
export function dataNoteSourceUrl(note: string | null | undefined): string | null {
  if (note === null || note === undefined) return null
  const match = note.match(/https?:\/\/[^\s)]+/)
  if (match === null) return null
  // Trailing punctuation is part of the sentence, not the URL.
  return match[0].replace(/[.,;]+$/, "")
}
