/**
 * GENERATED by `scripts/publish-journey-media.mjs`. DO NOT HAND-EDIT.
 *
 * A projection of `lib/media-manifest.ts` carrying only what the landing
 * journey renders. The manifest is 25,204 lines and is the authority; importing
 * it into a page to find eight photographs would pull the entire harvest into
 * the client graph, which is the budget this brief is graded on.
 *
 * Every entry here has been promoted to `attributed_display` in the manifest
 * and its files copied to `public/media`. No entry may carry
 * `subject: "unrelated"` - `scripts/journey-media-guard.mjs` asserts it.
 *
 * Regenerate: `node scripts/publish-journey-media.mjs`
 */

export type JourneyAct = "approach" | "complex" | "grounds" | "cut" | "room"

export interface JourneyImage {
  id: string
  act: JourneyAct
  width: number
  height: number
  aspectRatio: number
  /** Base64 WebP placeholder, straight from the manifest. */
  lqip: string
  /** Shown as a visible credit once per act. */
  publisher: string
  sourceUrl: string | null
  /** The listing that carried it is stale (SOURCES.md F-006). Labelled in the UI. */
  fromStaleListing: boolean
}

export interface JourneyVideo {
  slug: string
  act: JourneyAct
  src: string
  poster: string | null
}

/** Rungs published to `public/media`. Drives every `srcset`. */
export const JOURNEY_RUNGS = [800, 1200, 1600] as const

export const journeyImages: JourneyImage[] = [
  {
    "id": "azw-azuraworldhotel-com-69be5fa4ca5b",
    "act": "approach",
    "width": 1920,
    "height": 1278,
    "aspectRatio": 1.5023,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoUAA0ALtGIxGIkLCwsDADQSgCdIIjGZR+dsdIqmtjmAAD+kBdgbNzCl9gLCWmhG5bG4+zFdbwZjNPqrRWOy8dYAAA=",
    "publisher": "Azura World Hotel",
    "sourceUrl": "http://azuraworldhotel.com/en/gallery",
    "fromStaleListing": false
  },
  {
    "id": "azw-hasporealty-com-7c4bb03ab1c2",
    "act": "approach",
    "width": 2048,
    "height": 1152,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoUAAsAPxF4tFGsJyUisAgBgCIJbACdACHQRu6kOWIQv3NgAPpcWSoKQ1RpW0O24y/z5f7wgLIJzH1zdY+h4q7lkkmfAAAA",
    "publisher": "Haspo Realty",
    "sourceUrl": "https://hasporealty.com/de/complex/azura-world/",
    "fromStaleListing": true
  },
  {
    "id": "azw-housearch-com-989bab955ff8",
    "act": "approach",
    "width": 2400,
    "height": 1350,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAwCdASoUAAsAPxF6tFAsKCUisAgBgCIJYgCdAB428wNX7bMAAPeguOHqMTpmCZf/LY8sidtzo2Q+pfqOc9Y76KhQAA==",
    "publisher": "Housearch",
    "sourceUrl": "https://housearch.com/de/turkey/residential-complexes/azura-world-3403639/",
    "fromStaleListing": false
  },
  {
    "id": "azw-housearch-com-a5d50353394d",
    "act": "complex",
    "width": 2400,
    "height": 1350,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoUAAsAPxFysFAsJqSisAgBgCIJagCdMoACNqsIiX788oAA/H6AI3L89m0/N1ImDtAyxjhFO5W+onaGBPj6aydrqNiUL8PvbgWMJAAA",
    "publisher": "Housearch",
    "sourceUrl": "https://housearch.com/de/turkey/residential-complexes/azura-world-3403639/",
    "fromStaleListing": false
  },
  {
    "id": "azw-housearch-com-87a086f5e3b1",
    "act": "complex",
    "width": 2400,
    "height": 1350,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoUAAsAPxFysFAsJqSisAgBgCIJYgCdAAnLjgbE3EAA/FMdPQ2f0KO/3hoTxYSOFIlyq+FL4wTxEGm86e3iYQ6c6AAAAA==",
    "publisher": "Housearch",
    "sourceUrl": "https://housearch.com/de/turkey/residential-complexes/azura-world-3403639/",
    "fromStaleListing": false
  },
  {
    "id": "azw-hasporealty-com-0ac45f9403ae",
    "act": "complex",
    "width": 2048,
    "height": 1152,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoUAAsAPxF0tFEsJqUisAgBgCIJZACdAB6qEFzEKU/BYQAA/d2wrmK+RB18VgYWKu4kNc9UtC5UzWSTgKNdjXro4dFo5XQA",
    "publisher": "Haspo Realty",
    "sourceUrl": "https://hasporealty.com/de/complex/azura-world/",
    "fromStaleListing": true
  },
  {
    "id": "azw-housearch-com-f2903b62f3aa",
    "act": "complex",
    "width": 2400,
    "height": 1350,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoUAAsAPxF4slEsJ6SisAgBgCIJaACdACHDghkV057pYADxcclQa6Xvrm1IcmlA1n1qAHl5/blQZrN5KKqyZ7DWvKAAAA==",
    "publisher": "Housearch",
    "sourceUrl": "https://housearch.com/de/turkey/residential-complexes/azura-world-3403639/",
    "fromStaleListing": false
  },
  {
    "id": "azw-azuraworldhotel-com-19d34904ddb7",
    "act": "grounds",
    "width": 2400,
    "height": 1969,
    "aspectRatio": 1.2189,
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAwCdASoUABAAPxFwsFAsJiSisAgBgCIJZwDE2CB0FcjIWaaAK/QA+mA3lSHw904HMFtL4rWq6bPcx3NgAAAA",
    "publisher": "Azura World Hotel",
    "sourceUrl": "http://azuraworldhotel.com/en",
    "fromStaleListing": false
  },
  {
    "id": "azw-azuraworldhotel-com-4d29956b9d38",
    "act": "grounds",
    "width": 2400,
    "height": 1602,
    "aspectRatio": 1.4981,
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQBACdASoUAA0APxFysFAsJqSisAgBgCIJZACdMoR3Ir+ADiYrzJ1FYADhgg9Qq6LVzaRtk5D4bvHKgmZc87S8fw7CpmSlj9WN9pZJNc4ivv+AAAA=",
    "publisher": "Azura World Hotel",
    "sourceUrl": "http://azuraworldhotel.com/en/restaurants",
    "fromStaleListing": false
  },
  {
    "id": "azw-azuraworldhotel-com-507b55eb1bc5",
    "act": "grounds",
    "width": 2400,
    "height": 1602,
    "aspectRatio": 1.4981,
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAwCdASoUAA0APxF4tFGsJyUisAgBgCIJZwC/OB9CPuFUMliLLKAA/rncedevEnb8wlJRASfdKMkvpnmGTKkV5ngAAA==",
    "publisher": "Azura World Hotel",
    "sourceUrl": "http://azuraworldhotel.com/en/bars",
    "fromStaleListing": false
  },
  {
    "id": "azw-azuraworldhotel-com-fce38d965709",
    "act": "grounds",
    "width": 2400,
    "height": 1602,
    "aspectRatio": 1.4981,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoUAA0APxFysFCsJqSisAgBgCIJZACsACE8Vkl1zp19FAD+Zpq43OAqdkTmo6o0IZMlNZvVwXJWQppFCfFkLKU5VaUXQAAA",
    "publisher": "Azura World Hotel",
    "sourceUrl": "http://azuraworldhotel.com/en/restaurants",
    "fromStaleListing": false
  },
  {
    "id": "azw-enspride-com-f5e0ff7153a0",
    "act": "grounds",
    "width": 1755,
    "height": 972,
    "aspectRatio": 1.8056,
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4WAoAAAAQAAAAEwAACgAAQUxQSCQAAAARN6CgbRuGP+HeHRoRET+vgWGYjaSuyUqs0fmb3D+i/7EAvR9WUDggPAAAAJADAJ0BKhQACwA/EXSwUCwnJKKwCAGAIglnAAA9gOzizVoahgAA+bH8uitANXTyG9P4ou+msAQ2tAeAAA==",
    "publisher": "ENS Pride",
    "sourceUrl": "https://enspride.com/property/azura-world-residence-hotel-a-new-iconic-lifestyle-concept-in-alanya/",
    "fromStaleListing": false
  },
  {
    "id": "azw-housearch-com-9c459f37049c",
    "act": "grounds",
    "width": 2400,
    "height": 1350,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoUAAsAPxF0slCsJqSisAgBgCIJQBhQAPid6MyAAP0z13d04Ryj5jPpVdPPJ9VH0+hl1JTHxpgAAA==",
    "publisher": "Housearch",
    "sourceUrl": "https://housearch.com/de/turkey/residential-complexes/azura-world-3403639/",
    "fromStaleListing": false
  },
  {
    "id": "azw-terrarealestate-com-9fb4b52d19e4",
    "act": "cut",
    "width": 1600,
    "height": 900,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAwCdASoUAAsAPxF4slEsJ6SisAgBgCIJZwDKAB6Q/nwvM49TIAD+4bBN9ep7hvLzSk7N4GG8eKcAAAA=",
    "publisher": "TERRA Real Estate",
    "sourceUrl": "https://terrarealestate.com/project/azura-world-residence-and-villas",
    "fromStaleListing": false
  },
  {
    "id": "azw-terrarealestate-com-29ef854ddb91",
    "act": "cut",
    "width": 1600,
    "height": 900,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAwCdASoUAAsAPxF0sVCsJqSisAgBgCIJZwAASoLfgKReZvgAAP7rElctOIhT7RXO/mYq8np6OdB8DgAAAA==",
    "publisher": "TERRA Real Estate",
    "sourceUrl": "https://terrarealestate.com/project/azura-world-residence-and-villas",
    "fromStaleListing": false
  },
  {
    "id": "azw-terrarealestate-com-817f7411bbb2",
    "act": "cut",
    "width": 1600,
    "height": 900,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoUAAsAPxFysVAsJqSisAgBgCIJZwAASnpmO09Cg257gAD+10UiFsAfy/ad6XldM1Bgd6iRGdkuHAAA",
    "publisher": "TERRA Real Estate",
    "sourceUrl": "https://terrarealestate.com/project/azura-world-residence-and-villas",
    "fromStaleListing": false
  },
  {
    "id": "azw-cebecigroup-com-9ee92ba4404e",
    "act": "room",
    "width": 2048,
    "height": 1153,
    "aspectRatio": 1.7762,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABwAwCdASoUAAsAPxFysVAsJqSisAgBgCIJQBadAU1h0Mem+gAAobAI0XjlKKNE6J9zRW53gZT93xuMiCY+KU2hwAA=",
    "publisher": "Cebeci Group",
    "sourceUrl": "https://www.cebecigroup.com/en/azura-world-residence-hotel",
    "fromStaleListing": false
  },
  {
    "id": "azw-cebecigroup-com-8cb59c7f90fa",
    "act": "room",
    "width": 2048,
    "height": 1152,
    "aspectRatio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAwCdASoUAAsAPxFwsFAsJiSisAgBgCIJQBYdg9Iv56PbTNlcIAAA3LBoB+KIsBLFipcpZAXCOfE/hw6j6FOLh7iCdzAAAAA=",
    "publisher": "Cebeci Group",
    "sourceUrl": "https://www.cebecigroup.com/en/azura-world-residence-hotel",
    "fromStaleListing": false
  },
  {
    "id": "azw-cebecigroup-com-f8f351f7f676",
    "act": "room",
    "width": 2048,
    "height": 1153,
    "aspectRatio": 1.7762,
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwBACdASoUAAsAPxF0tFEsJqUisAgBgCIJZQC/OCIjYKayblYeqSydcAAA/Pm0uuJQqG6P62KGRidoCNwSoFusqNozl8uH7sWoPwsAAAA=",
    "publisher": "Cebeci Group",
    "sourceUrl": "https://www.cebecigroup.com/en/azura-world-residence-hotel",
    "fromStaleListing": false
  },
  {
    "id": "azw-cebecigroup-com-38f672f2d306",
    "act": "room",
    "width": 2048,
    "height": 1153,
    "aspectRatio": 1.7762,
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAwCdASoUAAsAPxGCtFIsKaUisAgBgCIJYwDG9BIt6uSp/AAA+125hi9JCYeB3tA2UfNNJo05m6IMrVk2AAAA",
    "publisher": "Cebeci Group",
    "sourceUrl": "https://www.cebecigroup.com/en/azura-world-residence-hotel",
    "fromStaleListing": false
  },
  {
    "id": "azw-cebecigroup-com-8bd9150c82bb",
    "act": "room",
    "width": 2048,
    "height": 1153,
    "aspectRatio": 1.7762,
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoUAAsAPxFwsFAsJiSisAgBgCIJZACdMoABwOJHD3SkAAD+tm0r6JwRf4xAPX1exQxdGAZdgNuRJJLnEDlASRoMVH87DZFwQAA=",
    "publisher": "Cebeci Group",
    "sourceUrl": "https://www.cebecigroup.com/en/azura-world-residence-hotel",
    "fromStaleListing": false
  },
  {
    "id": "azw-cebecigroup-com-1d8d94bffade",
    "act": "room",
    "width": 2048,
    "height": 1153,
    "aspectRatio": 1.7762,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoUAAsAPxF0slCsJqSisAgBgCIJZQCdABdfi9wzW1AAAP6zLSvroNxsq2JCrtzvbENG45LLalsiZAYNdn0nsvqIAAA=",
    "publisher": "Cebeci Group",
    "sourceUrl": "https://www.cebecigroup.com/en/azura-world-residence-hotel",
    "fromStaleListing": false
  }
]

export const journeyVideos: JourneyVideo[] = [
  {
    "slug": "film",
    "act": "complex",
    "src": "/media/azura-film.mp4",
    "poster": "/media/azura-film-poster.webp"
  }
]

export function imagesForAct(act: JourneyAct): JourneyImage[] {
  return journeyImages.filter((image) => image.act === act)
}

export function videoForAct(act: JourneyAct): JourneyVideo | null {
  return journeyVideos.find((video) => video.act === act) ?? null
}

/** `srcset` for one asset, AVIF or WebP. Paths are public, never `sources/`. */
export function srcSet(id: string, ext: "avif" | "webp"): string {
  return JOURNEY_RUNGS.map((w) => `/media/${id}-${w}.${ext} ${w}w`).join(", ")
}

/** The 1200 rung, as the `<img src>` fallback. */
export function fallbackSrc(id: string): string {
  return `/media/${id}-1200.webp`
}
