/**
 * F1 — proof that role resolution is fixed, against the LIVE database.
 *
 *   node --experimental-strip-types --import ./scripts/register-ts-resolve.mjs \
 *        HANDOFF/F1-role-resolution-probe.mts
 *
 * Reads `apps/web/.env.local` for the project URL and the service-role key.
 *
 * ## What this proves, and what it does not
 *
 * It drives the two things SEC-002 broke, both of them real:
 *
 *   1. the **projection** — `PROFILE_COLUMNS` from `lib/auth-resolution.ts`, issued verbatim
 *      to the live PostgREST;
 *   2. the **resolution** — `resolveSupabaseProfile()` from `lib/auth-resolution.ts`,
 *      the exported pure function `getUserProfile()` hands its result to.
 *
 * It runs the old select list first, so the failure and the fix are measured by
 * the same code on the same rows rather than argued about.
 *
 * **Not proved here: the session hop.** `supabase.auth.getUser()` needs a signed
 * cookie, the eleven seeded users have passwords generated by
 * `encode(gen_random_bytes(24),'base64')` with `azura.seed_password` unset, and
 * no password is recorded anywhere in the repository. Minting one is a
 * credential rotation, which is on the unattended never-do list, so this probe
 * stops at the boundary and says so. Nothing in the F1 change touches that hop:
 * the diff is a projection constant and two comments.
 */

import { readFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import {
  PROFILE_COLUMNS,
  resolveSupabaseProfile,
} from "../apps/web/lib/auth-resolution.ts"
import { roles as FROZEN_ROLES } from "../apps/web/lib/contracts.ts"

const HERE = path.dirname(fileURLToPath(import.meta.url))
const REPO = path.join(HERE, "..")

/** The list as it stood before F1, reproduced so the failure can be re-measured. */
const BROKEN_SELECT =
  "id, email, full_name, role, roles, is_active, anonymized_at, company_id, phone, locale, avatar_url"
const FIXED_SELECT = PROFILE_COLUMNS.join(", ")

function env(): { url: string; key: string } {
  const raw = readFileSync(path.join(REPO, "apps", "web", ".env.local"), "utf8")
  const pick = (name: string): string => {
    const line = raw.split(/\r?\n/).find((l) => l.startsWith(`${name}=`))
    if (line === undefined) throw new Error(`${name} missing from apps/web/.env.local`)
    return line.slice(name.length + 1).replace(/^["']|["']$/g, "").trim()
  }
  return { url: pick("NEXT_PUBLIC_SUPABASE_URL"), key: pick("SUPABASE_SERVICE_ROLE_KEY") }
}

const { url, key } = env()

async function selectProfiles(select: string) {
  const response = await fetch(
    `${url}/rest/v1/profiles?select=${encodeURIComponent(select)}&order=email`,
    { headers: { apikey: key, Authorization: `Bearer ${key}` } }
  )
  return { status: response.status, body: await response.json() }
}

let pass = 0
let fail = 0
const check = (label: string, ok: boolean, detail = "") => {
  if (ok) { pass += 1; console.log(`PASS  ${label}${detail ? `  ${detail}` : ""}`) }
  else { fail += 1; console.log(`FAIL  ${label}${detail ? `  ${detail}` : ""}`) }
}

console.log(`project: ${url.replace(/https:\/\/([^.]{4})[^.]*/, "https://$1…")}\n`)

// ---------------------------------------------------------------------------
console.log("=== 1. BEFORE — the select list as it shipped ===\n")
// ---------------------------------------------------------------------------
const before = await selectProfiles(BROKEN_SELECT)
console.log(`  HTTP ${before.status}  ${JSON.stringify(before.body).slice(0, 150)}\n`)
check(
  "the old projection is rejected by PostgREST",
  before.status === 400 && before.body?.code === "42703",
  `code=${before.body?.code}`
)

// A rejected read is exactly what `getUserProfile()` passed to the resolver.
const degraded = resolveSupabaseProfile({
  userId: "b0000000-0000-4000-8000-000000000001",
  userEmail: "admin@azura.local",
  profileReadFailed: true,
  row: null,
})
check(
  "…and the resolver therefore answered `tenant` for an administrator",
  degraded.role === "tenant",
  `role=${degraded.role} · ${degraded.degradedReason ?? ""}`
)

// ---------------------------------------------------------------------------
console.log("\n=== 2. AFTER — PROFILE_COLUMNS from lib/auth-resolution.ts ===\n")
// ---------------------------------------------------------------------------
console.log(`  ${FIXED_SELECT}\n`)
const after = await selectProfiles(FIXED_SELECT)
check("the fixed projection is accepted", after.status === 200, `HTTP ${after.status}`)
check(
  "every column requested came back",
  Array.isArray(after.body) &&
    after.body.length > 0 &&
    PROFILE_COLUMNS.every((c) => c in after.body[0]),
  `${PROFILE_COLUMNS.length} columns`
)

// ---------------------------------------------------------------------------
console.log("\n=== 3. Each of the eleven roles must resolve to ITSELF ===\n")
// ---------------------------------------------------------------------------
const rows: Array<Record<string, unknown>> = Array.isArray(after.body) ? after.body : []
console.log(`  ${"email".padEnd(32)} ${"stored".padEnd(18)} ${"resolved".padEnd(18)} roles[]`)
console.log(`  ${"-".repeat(84)}`)

const resolvedByRole = new Map<string, string>()
for (const row of rows) {
  const stored = String(row["role"])
  const profile = resolveSupabaseProfile({
    userId: String(row["id"]),
    userEmail: String(row["email"]),
    profileReadFailed: false,
    row,
  })
  const resolved = profile.authenticated ? profile.role : "ANONYMOUS"
  const list = profile.authenticated ? JSON.stringify(profile.roles) : "-"
  resolvedByRole.set(stored, resolved)
  const mark = resolved === stored ? " " : "!"
  console.log(`${mark} ${String(row["email"]).padEnd(32)} ${stored.padEnd(18)} ${resolved.padEnd(18)} ${list}`)
}

check("all eleven seeded profiles were read", rows.length === 11, `${rows.length} rows`)
check(
  "every role resolves to itself, none to tenant",
  [...resolvedByRole.entries()].every(([stored, resolved]) => stored === resolved),
  `${[...resolvedByRole.entries()].filter(([s, r]) => s === r).length}/${resolvedByRole.size} identical`
)
check(
  "the eleven frozen CONTRACTS §3 roles are all present, none invented",
  FROZEN_ROLES.every((r) => resolvedByRole.has(r)) && resolvedByRole.size === FROZEN_ROLES.length,
  `${resolvedByRole.size} distinct`
)
check(
  "admin resolves to admin, which is the whole point",
  resolvedByRole.get("admin") === "admin"
)
check(
  // A healthy profile carries `degradedReason: null`, not `undefined`. The
  // first version of this assertion tested `=== undefined` and failed against
  // correct code; the assertion was wrong, not the resolver.
  "no profile is degraded — every degradedReason is null",
  rows.every((row) => {
    const p = resolveSupabaseProfile({
      userId: String(row["id"]),
      userEmail: String(row["email"]),
      profileReadFailed: false,
      row,
    })
    return p.authenticated && (p.degradedReason ?? null) === null
  })
)

// ---------------------------------------------------------------------------
console.log("\n=== 4. The projection may not drift from the schema again ===\n")
// ---------------------------------------------------------------------------
const wide = await selectProfiles("*")
const actual: string[] = Array.isArray(wide.body) && wide.body[0] ? Object.keys(wide.body[0]) : []
const missing = PROFILE_COLUMNS.filter((c) => !actual.includes(c))
console.log(`  live columns: ${actual.sort().join(", ")}`)
check(
  "every column PROFILE_COLUMNS names exists in the live schema",
  missing.length === 0,
  missing.length ? `missing: ${missing.join(", ")}` : `${PROFILE_COLUMNS.length} of ${actual.length}`
)
check(
  "the two columns SEC-002 named are still absent, so the fix is the right one",
  !actual.includes("roles") && !actual.includes("anonymized_at")
)

console.log(`\n${pass} pass · ${fail} fail`)
process.exit(fail === 0 ? 0 : 1)
